[package]
name = "pg-core"
version.workspace = true
edition.workspace = true

[dependencies]
sea-orm.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
